#!/usr/bin/env bash
#
# Local deploy: build Ospore and lay it out as a self-contained runtime dir.
#
#   ./scripts/deploy.sh [target-dir]        default: ~/env/ospore
#
# Resulting layout:
#   <target>/app/        unpacked Electron build — replaced on every deploy
#   <target>/data/       OSPORE_DATA_DIR → ospore.db (+ WAL siblings) — never touched
#   <target>/config/env  KEY=VALUE config — generated once, never overwritten
#   <target>/run         launcher: sources config, exports OSPORE_DATA_DIR, execs app
#
# Start the deployed app with:  ~/env/ospore/run

set -euo pipefail

TARGET_DIR="${1:-$HOME/env/ospore}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UNPACKED="$REPO_ROOT/build-output/dist/linux-unpacked"

log() { printf '\033[1;32m[deploy]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[deploy]\033[0m %s\n' "$*" >&2; exit 1; }

command -v pnpm >/dev/null 2>&1 || die "pnpm not found in PATH"

# 1. Build the unpacked Electron distribution.
log "building: pnpm build:unpack"
cd "$REPO_ROOT"
pnpm build:unpack

# 2. Sanity-check the artifact before touching the runtime dir.
[ -x "$UNPACKED/ospore" ] || die "expected executable not found: $UNPACKED/ospore"

# 3. Replace app/ (product only — data/ and config/ survive deploys).
mkdir -p "$TARGET_DIR"
log "installing app -> $TARGET_DIR/app"
rm -rf "$TARGET_DIR/app"
cp -a "$UNPACKED" "$TARGET_DIR/app"

# 4. Ensure data/ and config/ exist; write config/env only on first deploy.
mkdir -p "$TARGET_DIR/data" "$TARGET_DIR/config"
if [ ! -f "$TARGET_DIR/config/env" ]; then
  log "writing $TARGET_DIR/config/env (first deploy only — edit freely afterwards)"
  cat > "$TARGET_DIR/config/env" <<'EOF'
# Ospore runtime config (KEY=VALUE, sourced by `run`).
# Deploy never overwrites this file.

# App data location. Defaults to <runtime>/data — set to override.
# OSPORE_DATA_DIR=
EOF
fi

# 5. Regenerate the launcher (ours — safe to rewrite on every deploy).
cat > "$TARGET_DIR/run" <<'EOF'
#!/usr/bin/env bash
# Generated by scripts/deploy.sh.
ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
set -a; [ -f "$ROOT/config/env" ] && . "$ROOT/config/env"; set +a
export OSPORE_DATA_DIR="${OSPORE_DATA_DIR:-$ROOT/data}"
mkdir -p "$OSPORE_DATA_DIR"
exec "$ROOT/app/ospore" "$@"
EOF
chmod +x "$TARGET_DIR/run"

log "done — start with: $TARGET_DIR/run"
